<?xml version="1.0" encoding="utf-8"?><Database Name="MicrosoftProjekat2" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="ConnectionString" ConnectionString="Data Source=DESKTOP-2B5P7KI;Initial Catalog=MicrosoftProjekat2;Integrated Security=True;TrustServerCertificate=True" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Clients" Member="Clients">
    <Type Name="Client">
      <Column Name="ClientID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClientName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Client_Order" Member="Orders" ThisKey="ClientID" OtherKey="Client_ClientID" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ProductPrice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Association Name="Product_Item" Member="Items" ThisKey="ProductID" OtherKey="Product_ProductID" Type="Item" />
    </Type>
  </Table>
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmployeeName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Employee_Order" Member="Orders" ThisKey="EmployeeID" OtherKey="Employee_EmployeeID" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.Items" Member="Items">
    <Type Name="Item">
      <Column Name="ItemID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemPrice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Order_OrderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Product_ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_Item" Member="Product" ThisKey="Product_ProductID" OtherKey="ProductID" Type="Product" IsForeignKey="true" />
      <Association Name="Order_Item" Member="Order" ThisKey="Order_OrderID" OtherKey="OrderID" Type="Order" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Employee_EmployeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Client_ClientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Order_Item" Member="Items" ThisKey="OrderID" OtherKey="Order_OrderID" Type="Item" />
      <Association Name="Client_Order" Member="Client" ThisKey="Client_ClientID" OtherKey="ClientID" Type="Client" IsForeignKey="true" />
      <Association Name="Employee_Order" Member="Employee" ThisKey="Employee_EmployeeID" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
</Database>